# CMake generated Testfile for 
# Source directory: /home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf
# Build directory: /home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/test/animation/offline/gltf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gltf2ozz_version]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--version")
set_tests_properties([=[gltf2ozz_version]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;13;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_bad_content]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/bad.unk")
set_tests_properties([=[gltf2ozz_bad_content]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Failed to import file \"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/bad.unk\"." _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;14;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_bad_content_gltf]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/bad.gltf")
set_tests_properties([=[gltf2ozz_bad_content_gltf]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Failed to import file \"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/bad.gltf\"." _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;16;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_bad_content_glb]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/bad.glb")
set_tests_properties([=[gltf2ozz_bad_content_glb]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Failed to import file \"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/bad.glb\"." _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;18;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_skel_no_animation]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/triangle.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_skeleton_24.ozz\",\"import\":{\"enable\":true}},\"animations\":[{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_should_not_exist.ozz\",\"clip\":\"*\"}]}")
set_tests_properties([=[gltf2ozz_skel_no_animation]=] PROPERTIES  PASS_REGULAR_EXPRESSION "No animation found." _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;24;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_skel_no_matching_animation]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/interpolation_test.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_skeleton_27.ozz\",\"import\":{\"enable\":true}},\"animations\":[{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_should_not_exist.ozz\",\"clip\":\"won_t_match\"}]}")
set_tests_properties([=[gltf2ozz_skel_no_matching_animation]=] PROPERTIES  PASS_REGULAR_EXPRESSION "No matching animation found" _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;27;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_skel_output]=] "/usr/bin/cmake" "-E" "copy" "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_should_not_exist.ozz" "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_should_not_exist_too.ozz")
set_tests_properties([=[gltf2ozz_skel_output]=] PROPERTIES  DEPENDS "gltf2ozz_skel_no_skeleton" WILL_FAIL "true" _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;33;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_skel_simple]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/interpolation_test.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_interpolation_test_skeleton.ozz\",\"import\":{\"enable\":true}}}")
set_tests_properties([=[gltf2ozz_skel_simple]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;41;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_skel_box_animated]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/box_animated.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_box_animated_skeleton.ozz\",\"import\":{\"enable\":true}}}")
set_tests_properties([=[gltf2ozz_skel_box_animated]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;43;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_skel_cesium]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/cesium_man.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_cesium_man_skeleton.ozz\",\"import\":{\"enable\":true}}}")
set_tests_properties([=[gltf2ozz_skel_cesium]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;45;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_animation_multiple]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/interpolation_test.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_interpolation_test_skeleton.ozz\",\"import\":{\"enable\":false}},\"animations\":[{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_interpolation_test_*.ozz\"}]}")
set_tests_properties([=[gltf2ozz_animation_multiple]=] PROPERTIES  DEPENDS "gltf2ozz_skel_simple" _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;50;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_box_animation]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/box_animated.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_box_animated_skeleton.ozz\",\"import\":{\"enable\":false}},\"animations\":[{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_box_animation.ozz\"}]}")
set_tests_properties([=[gltf2ozz_box_animation]=] PROPERTIES  DEPENDS "gltf2ozz_skel_box_animated" _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;53;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[gltf2ozz_cesium_animation]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/src/animation/offline/gltf/gltf2ozz" "--file=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/media/gltf/khronos/cesium_man.gltf" "--config={\"skeleton\":{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_cesium_man_skeleton.ozz\",\"import\":{\"enable\":false}},\"animations\":[{\"filename\":\"/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_cesium_man_animation.ozz\"}]}")
set_tests_properties([=[gltf2ozz_cesium_animation]=] PROPERTIES  DEPENDS "gltf2ozz_skel_cesium" _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;56;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
add_test([=[sample_playback_gltf_ruby]=] "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/samples/playback/sample_playback" "--skeleton=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_ruby_skeleton.ozz" "--animation=/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation-build/temp/gltf_ruby_animation.ozz" "--max_idle_loops=20" "--norender")
set_tests_properties([=[sample_playback_gltf_ruby]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;77;add_test;/home/sebastiang/prototypevulkangame/Mineanarchy/ozz-animation/test/animation/offline/gltf/CMakeLists.txt;0;")
